-- MySQL Script generated by MySQL Workbench
-- Tue May 16 16:38:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema telefonia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `telefonia` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `telefonia` DEFAULT CHARACTER SET utf8 ;
USE `telefonia` ;

-- -----------------------------------------------------
-- Table `telefonia`.`operador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`operador` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`operador` (
  `idoperador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idoperador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`sim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`sim` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`sim` (
  `idsim` INT NOT NULL AUTO_INCREMENT,
  `imei` INT NULL,
  `numeroTelefono` INT NULL,
  `operador_idoperador` INT NOT NULL,
  PRIMARY KEY (`idsim`, `operador_idoperador`),
  INDEX `fk_sim_operador_idx` (`operador_idoperador` ASC) ,
  CONSTRAINT `fk_sim_operador`
    FOREIGN KEY (`operador_idoperador`)
    REFERENCES `telefonia`.`operador` (`idoperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`llamada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`llamada` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`llamada` (
  `idllamada` INT NOT NULL AUTO_INCREMENT,
  `id_simOrigen` INT NULL,
  `id_simDestino` INT NULL,
  `fecha` VARCHAR(45) NULL,
  `duracion` FLOAT NULL,
  `coste` FLOAT NULL,
  `sim_idsim` INT NOT NULL,
  `sim_operador_idoperador` INT NOT NULL,
  PRIMARY KEY (`idllamada`, `sim_operador_idoperador`, `sim_idsim`),
  INDEX `fk_llamada_sim1_idx` (`sim_idsim` ASC, `sim_operador_idoperador` ASC) ,
  CONSTRAINT `fk_llamada_sim1`
    FOREIGN KEY (`sim_idsim` , `sim_operador_idoperador`)
    REFERENCES `telefonia`.`sim` (`idsim` , `operador_idoperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
